### ISSUE TITLE
"list indices must be integers, not str"

### ISSUE THREAD

**Issue by wpccolorblind** [egermano/slack-files-delete#3]
Get this after running the script and successfully deleting 20 or so files.  Re-running deletes another 20, and so on.

**Comment by egermano** [comment]
Let me check what happen.

**Comment by egermano** [comment]
Hi @wpccolorblind I tried and found the same issue. 

I just fix in this commit: d6e4889f6aa7515f6bed1cf9f8b72d5c77ca47fc

Works for me, can you try?
