### ISSUE TITLE
After deleting several files, the script ends

### ISSUE THREAD

**Issue by simPod** [egermano/slack-files-delete#5]
The script deletes several files and then fails with `list indices must be integers, not str` message.
![image](https://cloud.githubusercontent.com/assets/327717/16656040/5c91188e-445d-11e6-8d78-a851aa047f3b.png)

**Comment by egermano** [comment]
Sorry about the delay, do you have more info about this erro, like the number of file, the environment that runs this script.

Thank you.

**Comment by simPod** [comment]
No :D
